language: rust
node_js:
  - 10
before_install:
  - nvm install 10
  - nvm use 10
  - node -v
  - chmod +x wasm-pack-install.sh && sh -s -- -f wasm-pack-install.sh
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn build
  - yarn test
before_deploy:
  - travis_wait 20 yarn build-website
env:
  - CI=true
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build-website
  github-token: $GITHUB_TOKEN
  fqdn: dprint.dev
  keep-history: true
  on:
    branch: master
