[package]
name = "ts-dprint-plugin-typescript"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.58"
js-sys = "0.3.29"
dprint-core = { path = "../../rust-core", version = "0.6.0" }
dprint-plugin-typescript = { path = "../../rust-dprint-plugin-typescript", version = "0.1.0" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
