[package]
name = "dprint"
version = "0.3.1"
authors = ["Bartek Iwa≈Ñczuk <biwanczuk@gmail.com>", "David Sherret<dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint."
repository = "https://github.com/dprint/dprint"

[dependencies]
clap = "2.33.0"
dprint-core = { path = "../rust-core", version = "0.19.0" }
dprint-plugin-typescript = { path = "../rust-dprint-plugin-typescript", version = "0.17.0" }
dprint-plugin-jsonc = { path = "../rust-dprint-plugin-jsonc", version = "0.2.1" }
globwalk = "0.8.0"
jsonc-parser = { version = "0.5.0" }
rayon = "1.1"

[dev-dependencies]
globset = "0.4.5"
