[package]
name = "dprint-playground-wasm"
version = "0.1.0"
authors = ["David Sherret"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.58"
js-sys = "0.3.29"
dprint-plugin-typescript = { path = "../../rust-dprint-plugin-typescript" }
serde_json = "1.0"