[package]
name = "dprint"
version = "0.37.1"
authors = ["dprint code formatting <david@dprint.dev>"]
categories = ["development-tools"]
default-run = "dprint"
edition = "2021"
keywords = ["code-formatter", "formatter"]
license = "MIT"
repository = "https://github.com/dprint/dprint"
description = "Binary for dprint code formatterâ€”a pluggable and configurable code formatting platform."

[dependencies]
anyhow = "1.0.69"
clap = "4.3.8"
clap_complete = "4.3.1"
console_static_text = "0.7.1"
# don't upgrade to 0.26 https://github.com/crossterm-rs/crossterm/issues/752
crossterm = "0.25.0" # manually retest everything when bumping this crate
dirs = "4.0.0"
dprint-core = { path = "../core", version = "0.62.1", features = ["process", "wasm"] }
dunce = "1.0.3"
futures = "0.3.26"
ignore = "0.4.20"
indexmap = { version = "1.9.2", features = ["serde-1"] }
jsonc-parser = { version = "0.21.0" }
once_cell = "1.17.1"
parking_lot = "0.12.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha2 = "0.10.6"
similar = { version = "2.2.1", features = ["inline"] }
thiserror = "1"
tokio = { version = "1", features = ["rt", "time", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.7" }
twox-hash = "1.6.3"
ureq = { version = "2.6.2", features = ["socks-proxy", "tls", "native-certs"] }
url = "2.3.1"
zip = "0.6.4"

# pin these to prevent them changing with `cargo install` because
# patch version increases of rkyv may cause panics when deserializing
# data serialized with older versions
rkyv = "=0.7.42"
wasmer = "=4.0.0"
wasmer-compiler = "=4.0.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[dev-dependencies]
path-clean = "0.1.0"
pretty_assertions = "1.3.0"
