[package]
name = "dprint"
version = "0.4.0-beta2"
authors = ["David Sherret <dsherret@gmail.com>", "Bartek Iwa≈Ñczuk <biwanczuk@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint."
repository = "https://github.com/dprint/dprint"

[dependencies]
clap = "2.33.0"
dprint-core = { path = "../core", version = "0.20.0" }
dialoguer = "0.6.2"
globwalk = "0.8.0"
jsonc-parser = { version = "0.12.1" }
indicatif = "0.14.0"
reqwest = { version = "0.10.4" }
bytes = "0.5.4"
futures = { version = "0.3.4", features = ["compat", "io-compat"] }
tokio = { version = "0.2", features = ["full", "blocking"] }
async-trait = "0.1.30"
app_dirs = "1.2.1"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
wasmer-runtime = "0.17.0"
wasmer-runtime-core="0.17.0"

[dev-dependencies]
globset = "0.4.5"
lazy_static = "1.4.0"
pretty_assertions = "0.6.1"
