[package]
name = "dprint"
version = "0.18.2"
authors = ["dprint code formatting <david@dprint.dev>"]
categories = ["development-tools"]
edition = "2021"
keywords = ["code-formatter", "formatter"]
license = "MIT"
repository = "https://github.com/dprint/dprint"
description = "Binary for dprint code formatterâ€”a pluggable and configurable code formatting platform."

[dependencies]
clap = "2.33.3"
crossterm = "0.21.0"
dirs = "4.0.0"
dprint-cli-core = { path = "../cli-core", version = "0.9.1" }
dprint-core = { path = "../core", version = "0.47.0", features = ["process", "wasm"] }
dunce = "1.0.2"
ignore = "0.4.18"
jsonc-parser = { version = "0.17.0" }
num_cpus = "1.13.0"
parking_lot = "0.11.2"
rayon = "1.5.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
similar = { version = "2.1.0", features = ["inline"] }
twox-hash = "1.6.1"
url = "2.2.2"
wasmer = "=2.0.0"
wild = "2.0.4"
zip = "0.5.13"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[dev-dependencies]
lazy_static = "1.4.0"
path-clean = "0.1.0"
pretty_assertions = "1.0.0"
