[package]
name = "dprint"
version = "0.11.0"
authors = ["dprint code formatting <david@dprint.dev>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint code formatterâ€”a pluggable and configurable code formatting platform."
repository = "https://github.com/dprint/dprint"
keywords = ["code-formatter", "formatter"]
categories = ["development-tools"]

[dependencies]
clap = "2.33.0"
crossterm = "0.18.2"
dunce = "1.0.1"
dprint-core = { path = "../core", version = "0.33.1", features = ["process", "wasm"] }
dprint-cli-core = { path = "../cli-core", version = "0.5.2" }
dissimilar = "1.0"
globwalk = "0.8.0"
jsonc-parser = { version = "0.14.0" }
parking_lot = "0.11.0"
dirs = "3.0.1"
num_cpus = "1.13.0"
rayon = "1.4.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
twox-hash = "1.5.0"
url = "2.1.1"
wasmer = "=1.0.0-alpha5"
zip = "0.5.8"

[dev-dependencies]
globset = "0.4.5"
lazy_static = "1.4.0"
pretty_assertions = "0.6.1"
path-clean = "0.1.0"
