[package]
name = "dprint"
version = "0.15.1"
authors = ["dprint code formatting <david@dprint.dev>"]
categories = ["development-tools"]
edition = "2018"
keywords = ["code-formatter", "formatter"]
license = "MIT"
repository = "https://github.com/dprint/dprint"
description = "Binary for dprint code formatterâ€”a pluggable and configurable code formatting platform."

[dependencies]
clap = "2.33.3"
crossterm = "0.20.0"
dirs = "3.0.2"
dissimilar = "1.0"
dprint-cli-core = { path = "../cli-core", version = "0.7.0" }
dprint-core = { path = "../core", version = "0.44.0", features = ["process", "wasm"] }
dunce = "1.0.2"
globset = "0.4.8"
globwalk = "0.8.1"
jsonc-parser = { version = "0.17.0" }
num_cpus = "1.13.0"
parking_lot = "0.11.1"
rayon = "1.5.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
twox-hash = "1.6.0"
url = "2.2.2"
wasmer = "=2.0.0"
wild = "2.0.4"
zip = "0.5.13"

[target.'cfg(windows)'.dependencies]
winreg = "0.9.0"

[dev-dependencies]
globset = "0.4.8"
lazy_static = "1.4.0"
path-clean = "0.1.0"
pretty_assertions = "0.7.2"
