[package]
name = "dprint-development"
version = "0.9.2"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Helper functions for testing dprint plugins."

[dependencies]
anyhow = "1.0.66"
console = "0.15.2"
indexmap = "1.9.2"
similar = "2.2.1"
