[package]
name = "test-process-plugin"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2024"

[dependencies]
anyhow.workspace = true
dprint-core = { path = "../core", features = ["process"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
