[package]
name = "test-process-plugin"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"

[dependencies]
dprint-core = { path = "../core", features = ["process"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
