[package]
name = "dprint-core"
description = "Core rust library for dprint."
keywords = ["formatting", "formatter"]
version = "0.35.2"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dprint/dprint/tree/master/crates/core"
repository = "https://github.com/dprint/dprint"

[features]
default = ["formatting"]

formatting = ["bumpalo", "fnv"]
process = ["serde_json", "sysinfo"]
wasm = []

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
sysinfo = { version = "0.15.0", optional = true }
bumpalo = { version = "3.4.0", optional = true }
fnv = { version = "1.0.3", optional = true }