[package]
name = "dprint-plugin-typescript"
description = "TypeScript formatter for dprint."
keywords = ["formatting", "formatter", "typescript"]
version = "0.3.0-alpha.6"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dsherret/dprint/tree/master/packages/rust-dprint-plugin-typescript"
repository = "https://github.com/dsherret/dprint"

[dependencies]
dprint-core = { path = "../rust-core", version = "0.7.0-alpha.4" }
swc_common = "0.4.6"
swc_ecma_ast = "0.15.0"
swc_ecma_parser = "0.17.2"
serde = { version = "1.0.88", features = ["derive"] }

[dev-dependencies]
dprint-development = { path = "../rust-development" }
debug-here = "0.2"
